### PR TITLE
Update readme on how to run

### PR DESCRIPTION
**Pull request by PanMan**
Tiny change, but I was looking on how to run it after first boot.

### CODE REVIEW

**Comment by spl237** [comment]
Unfortunately, that's not quite correct - it needs to be run with sudo... Can you please amend accordingly and resubmit, and I'll pull it in?

Many thanks.

**Comment by PanMan** [comment]
Thanks, learning stuff here. It did run without sudo, and asked for password later when installing things

**Comment by spl237** [comment]
Great, many thanks - merged.

FYI, a lot of it will work properly without sudo, but there are a few places where not using sudo causes subtle changes in behaviour.

**Comment by PanMan** [comment]
Yep, I did end up rerunning it with sudo 🙄 .
Perhaps unrelated, but it won't allow me to set my locale to NL but language to EN? Not everybody here speaks dutch. Now my Pi thinks it's in london.. 
Thanks!

**Comment by spl237** [comment]
That's a Debian limitation, unfortunately - locales are a fixed combination of country and language, and en_NL is not a combination that Debian offers. FYI, there is a list of all valid country and language combinations in /usr/share/i18n/SUPPORTED

**Comment by PanMan** [comment]
Thanks!

**Pull request merged**
